Add pupa clean CLI command
opencivicdata/pupa pull request #344
Opened 2023-02-20 17:17 UTC by antidipyramid

## Overview

This PR adds a new pupa CLI command: `pupa clean`:

>usage: pupa clean [-h] [--window WINDOW] [--report] [--noinput]
>
>Removes database objects that haven't been seen in recent scrapes
>
>optional arguments:
>  -h, --help       show this help message and exit
>  --window WINDOW  objects not seen in this many days will be deleted from the database
>  --report         only generate a report of what objects this command would delete without making any changes to the database
>  --noinput        delete objects without getting user confirmation

## Testing Instructions

* Make sure tests pass

2023-03-07 17:27 UTC, hancush requested changes
This is looking great, @antidipyramid! Excited to bring this over the line. Left a few things inline.

2023-03-07 17:27 UTC, hancush commented on pupa/cli/commands/clean.py
> +    return itertools.chain(*results)
What do you think about making this a generator (yielding from results) instead of building up a list?

2023-03-07 17:27 UTC, hancush commented on pupa/cli/commands/clean.py
> +    models = get_subclasses(ocd_apps, OCDBase)
Clever!!

2023-03-07 17:27 UTC, hancush commented on pupa/cli/commands/clean.py
> +                    return
I like to use [sys.exit()](https://docs.python.org/3.8/library/sys.html#sys.exit) so it's explicit what's going on. You can pass a 0 exit code if you want a No to still be considered a successful run.

2023-03-07 17:27 UTC, hancush commented on pupa/cli/commands/clean.py
> +def get_stale_objects(window):
How about adding this to the command class, as well?

2023-03-14 20:01 UTC, antidipyramid commented on pupa/tests/clean/test_clean.py
> +import pytest
That sounds like a good idea. Do you mean just calling `Command.handle()` and testing the output?

2023-03-14 20:03 UTC, hancush commented on pupa/tests/clean/test_clean.py
> +import pytest
I'd actually test that the command removes the data I expect and doesn't touch anything else.

2023-03-14 20:38 UTC, antidipyramid commented on pupa/cli/commands/clean.py
> +                )
Since we already have a report option, would a count of objects to be deleted be enough?

2023-03-16 14:22 UTC, hancush approved these changes
One small thing inline, then this can come in. This is really cool!

2023-03-16 14:22 UTC, hancush commented on pupa/cli/commands/clean.py
> +                    f" {len(self.get_stale_objects(args.window))}"
If this is a generator, I think you need to do:

```suggestion
                    f" {len(list(self.get_stale_objects(args.window)))}"
```

2023-03-16 20:36 UTC, merged

2023-03-16 20:42 UTC, hancush commented
Connects https://github.com/Metro-Records/la-metro-councilmatic/issues/900